import type { TemplateDefinition } from "@/lib/types";
import { resolveTemplates } from "./resolve-template";

/** 기존 제출 호환용 — 홈 목록에는 표시하지 않음 */
export const LEGACY_TEMPLATE_REGISTRY: TemplateDefinition[] = resolveTemplates([
  {
    id: "hot-spots",
    order: 99,
    name: "Hot Spots",
    category: "concept-exploration",
    description: "사진에서 눈에 띄는 부분",
    legacy: true,
    headerFields: ["writingContext"],
  },
  {
    id: "circle-tree-map",
    order: 99,
    name: "써클맵·트리맵",
    category: "concept-synthesis",
    description: "브레인스토밍과 분류",
    legacy: true,
    headerFields: ["writingContext"],
  },
  {
    id: "double-bubble-map",
    order: 99,
    name: "더블 버블 맵",
    category: "concept-synthesis",
    description: "두 대상 비교·대조",
    legacy: true,
    headerFields: ["writingContext"],
  },
  {
    id: "multi-flow-map",
    order: 99,
    name: "멀티플로우맵",
    category: "concept-synthesis",
    description: "원인·사건·결과 분석",
    legacy: true,
    headerFields: ["writingContext"],
  },
  {
    id: "bridge-map",
    order: 99,
    name: "브릿지맵",
    category: "concept-synthesis",
    description: "유추 관계 표현",
    legacy: true,
    headerFields: ["writingContext"],
  },
  {
    id: "hexagon-keywords",
    order: 99,
    name: "육각형 핵심 단어 연결하기",
    category: "concept-synthesis",
    description: "키워드와 연결 관계",
    legacy: true,
    headerFields: ["writingContext"],
  },
  {
    id: "swot",
    order: 99,
    name: "SWOT 기법",
    category: "concept-synthesis",
    description: "강점·약점·기회·위협",
    legacy: true,
    headerFields: ["writingContext"],
  },
  {
    id: "t-chart",
    order: 99,
    name: "T Chart",
    category: "concept-synthesis",
    description: "알게 된 것·알고 싶은 것",
    legacy: true,
    headerFields: ["description"],
  },
  {
    id: "y-chart",
    order: 99,
    name: "Y Chart",
    category: "concept-synthesis",
    description: "Looks·Sounds·Feels",
    legacy: true,
    headerFields: ["description"],
  },
  {
    id: "question-types",
    order: 99,
    name: "질문의 종류",
    category: "concept-exploration",
    description: "사실·개념·호기심 질문",
    legacy: true,
    headerFields: ["unit", "period", "inquiryQuestion", "writingContext"],
  },
  {
    id: "exaggeration",
    order: 99,
    name: "과장하기",
    nameEn: "Exaggeration",
    category: "concept-deepening",
    description: "과장 질문 기법",
    legacy: true,
    headerFields: ["description"],
  },
]);
